# Generated by Django 5.1.4 on 2024-12-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_remove_noticia_autor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Voo',
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='categoria',
            new_name='Voo',
        ),
    ]
